// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantManagementSystem.src.Infrastructure.Db;

#nullable disable

namespace RestaurantManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230926162430_RenamedMigrationFromAddedTableToDbToAddedTableRegistrationRequestsToDb")]
    partial class RenamedMigrationFromAddedTableToDbToAddedTableRegistrationRequestsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantManagementSystem.src.Core.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RegistrationRequests", (string)null);
                });

            modelBuilder.Entity("RestaurantManagementSystem.src.Core.Entities.RegistrationRequest", b =>
                {
                    b.OwnsOne("RestaurantManagementSystem.src.Core.Entities.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("RegistrationRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactEmail")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ContactEmail");

                            b1.Property<string>("ContactPhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ContactPhoneNumber");

                            b1.HasKey("RegistrationRequestId");

                            b1.ToTable("RegistrationRequests");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationRequestId");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
